### ISSUE TITLE
Anyone else getting 0 active connections on the new v0.24.2.0 for mac?

### ISSUE THREAD

**Issue by ajsingh007** [Xcgtech/Wallet#6]
I'm getting 0 active connections after updating my wallet locally -- curious if anyone else is experiencing the same?

**Comment by cryptforall** [comment]
Try clearbanned. if that doesn't work, try deleting everything except for wallet.dat and xchange.conf/masternode.conf in the roaming folder and restart the version 24.2.0 wallet.

**Comment by ajsingh007** [comment]
Hey cryptforall, thanks for the rapid response. Excuse my lack of knowledge, What is clearbanned??

**Comment by ajsingh007** [comment]
nevermind, I punched cleanbanned into the debug console with no luck. I proceeded to delete everything other than wallet.dat, xchange.conf, and masternode.conf in the XchangeCore directory and restarted... still 0 connections

**Comment by ajsingh007** [comment]
Update - switched to a different internet connection and it appears to be connected and resyncing. Will close for now

**Comment by cryptforall** [comment]
thanks for the update ajsingh007
